# Default post-review prompt for executable documents
# Workflow: POST_REVIEW (executable post-release review)

checklist:
  - category: Frontmatter
    items:
      - text: "`title:` field present and non-empty"
        evidence_prompt: "quote actual value"
      - text: "`revision_summary:` present and descriptive (required for v1.0+)"
        evidence_prompt: "quote actual value or N/A"

  - category: Document Structure
    items:
      - text: "Document follows type-specific template"
      - text: "All required sections present"
      - text: "Section numbering sequential and correct"

  - category: Content Integrity
    items:
      - text: "No placeholder text (TBD, TODO, XXX, FIXME)"
      - text: "No obvious factual errors or contradictions"
      - text: "References to other documents are valid"
      - text: "No typos or grammatical errors"
      - text: "Formatting consistent throughout"

critical_reminders:
  - "**Compliance is BINARY**: Document is either compliant or non-compliant"
  - "**ONE FAILED ITEM = REJECT**: No exceptions, no \"minor issues\""
  - "**VERIFY WITH EVIDENCE**: Quote actual values, do not assume"
  - "**REJECTION IS CORRECT**: A rejected document prevents nonconformance"
